### PR TITLE
Prepare pypi regsiter

### PR DESCRIPTION
**Pull request by tell-k**
I prepared to register PyPI(https://pypi.python.org/pypi).

- Add MANIFEST.in, setup.cfg
- Change README.md to README.rst. Because i want to use README as [long description](https://github.com/tell-k/woothee-python/compare/prepare_pypi_regsiter?expand=1#diff-2eeaed663bd0d25b7e608891384b7298R13).
- Select classfiers in setup.py from https://pypi.python.org/pypi?%3Aaction=list_classifiers 

You can try to regsiter PyPI.

1. You shuold to update Authors information in setup.py. 
2. Regsiter to PyPI(https://pypi.python.org/pypi?%3Aaction=register_form))
3. python setup.py register
4. python setup.py release

 - "release" shortcut is defined setup.cfg

5. You can confirm to uploaded to https://pypi.python.org/pypi/woothee/

see also [Tutorial on Packaging and Distributing Projects](https://packaging.python.org/en/latest/distributing.html)

If you are busy. I'll register it instead of you. :)

thx.

### CODE REVIEW

**Comment by tagomoris** [comment]
Could you become a maintainer of this repository & pypi release?
I cannot control so many language implementations anymore...

**Comment by methane** [comment]
Looking very nice to me.

**Comment by tell-k** [comment]
@tagomoris 

Thanks for your reply.
Sure. Leave it to me!

Please give me access permission of the repository whenever you would like to.
I'll change me a package of owner in setup.py. 

@methane

Thanks for your checking.

**Comment by tagomoris** [comment]
@tell-k I made woothee-python-team, and added you to it!

**Comment by tagomoris** [comment]
:+1:

**Comment by tell-k** [comment]
@tagomoris
 
I have just finished to upload it.
https://pypi.python.org/pypi/woothee/
Please try it if you feel free.
Thx.

**Pull request merged**
